manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
    - name: eintim
      url-base: https://github.com/eintim
    - name: kloir-z
      url-base: https://github.com/kloir-z
    - name: kot149
      url-base: https://github.com/kot149
    - name: ssbb
      url-base: https://github.com/ssbb
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kloir-z
      revision: 96b23443cb6aae0f182aaa5f4109582e6afdd5dc
    - name: zmk-behavior-battery-typer
      remote: eintim
      revision: main
    - name: zmk-mouse-gesture
      remote: kot149
      revision: v1
    - name: zmk-listeners
      remote: ssbb
      revision: v1
  self:
    path: config
