CONFIG_ZMK_KEYBOARD_NAME="roBa"

CONFIG_ZMK_POINTING=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y

CONFIG_I2C=y
CONFIG_INPUT=y
CONFIG_INPUT_IQS9151=y

# トラックパッドの回転設定 (左に90度回転 = 270度)
CONFIG_INPUT_IQS9151_ROTATE_0=n
CONFIG_INPUT_IQS9151_ROTATE_270=y

# トラックパッドの慣性設定
CONFIG_INPUT_IQS9151_CURSOR_INERTIA_DECAY=940
CONFIG_INPUT_IQS9151_SCROLL_INERTIA_DECAY=800

# 強く弾いた時だけカーソルに慣性を効かせる（デフォルト10 → 40）
CONFIG_INPUT_IQS9151_CURSOR_INERTIA_MIN_AVG_SPEED=40

# 3本指タップの有効化（中クリックとして機能）
CONFIG_INPUT_IQS9151_3F_TAP_ENABLE=y
CONFIG_INPUT_IQS9151_3F_PRESSHOLD_ENABLE=y

# 3本指スワイプの有効化
CONFIG_INPUT_IQS9151_3F_SWIPE_THRESHOLD=200

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n 

CONFIG_ZMK_MOUSE_GESTURE=y
